#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use DBI;

require '/home/eli/photo-gallery/db-funcs.pm';

use vars qw( $rc $dbh 
	     $tag $clean $id
	     );

$dbh = ark::dbconnect();

while($tag = shift) {
  $clean = ark::clean_tag( $tag );

  $id = ark::find_or_create_tag($dbh, $tag);

  print "$id\t$clean\t$tag\n"
}

$rc  = $dbh->disconnect;
__END__
