#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use DBI;
use JSON::PP;

use vars qw( $rc
	     $dbh $statement
	     $ark_tag_search_statement
	     $frag $tag @tags
	     $num
	     );

$num = 15;

$rc = do '/home/eli/photo-gallery/db-funcs.pm';
if(!defined($rc)) { die "Failed to load db functions file\n"; }

$frag = clean_tag($ARGV[0] or 'help');

$dbh = dbconnect();

$statement = $dbh->prepare( $ark_tag_search_statement );
$statement->execute( "%$frag%", $num );

# fetchall_arrayref returns a one element array for every row
# the map removes the inner arrays
my $result = $statement->fetchall_arrayref();
@tags = map { $$_[0] } @$result;

$rc  = $dbh->disconnect;

$" = "\n\t"; # list separator for quoted arrays
print "Top $num matches:\n\t@tags\n";
__END__
