#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use DBI;
use JSON::PP;

require '/home/eli/photo-gallery/db-funcs.pm';

use vars qw( $rc
	     $dbh $statement
	     $frag $tag @tags
	     $num
	     );

$num = 15;

$frag = $ARGV[0] or 'help';

$dbh = ark::dbconnect();

@tags = ark::tag_fragment_search($dbh, $frag, $num);

$rc  = $dbh->disconnect;

$" = "\n\t"; # list separator for quoted arrays
print "Top $num matches:\n\t@tags\n";
__END__
